from arketype_API.ark import Ark
from sparql_triplestore.sparql_requests.sparql_generic_post_methods import SparqlGenericPostMethods
from sparql_triplestore.sparql_requests.person.sparql_get_person_methods import SparqlGetPersonMethods
from sparql_triplestore.sparql_requests.person.sparql_post_person_methods import SparqlPostPersonMethods
from sparql_triplestore.sparql_requests.article.sparql_get_article_methods import SparqlGetArticleMethods
from sparql_triplestore.sparql_requests.article.sparql_post_article_methods import SparqlPostArticleMethods
from sparql_triplestore.sparql_requests.project.sparql_get_project_methods import SparqlGetProjectMethods
from sparql_triplestore.sparql_requests.project.sparql_post_project_methods import SparqlPostProjectMethods
from sparql_triplestore.sparql_requests.dataset.sparql_get_dataset_methods import SparqlGetDatasetMethods
from sparql_triplestore.sparql_requests.dataset.sparql_post_dataset_methods import SparqlPostDatasetMethods
from sparql_triplestore.sparql_requests.institution.sparql_get_institution_methods import SparqlGetInstitutionMethods
from sparql_triplestore.sparql_requests.institution.sparql_post_institution_methods import SparqlPostInstitutionMethods
from sparql_triplestore.sparql_requests.funder.sparql_get_funder_methods import SparqlGetFunderMethods
from sparql_triplestore.sparql_requests.funder.sparql_post_funder_methods import SparqlPostFunderMethods
import sparql_triplestore.sparql_requests.variables as sparql_variables


ark = Ark()
sparql_generic_post_object = SparqlGenericPostMethods()
sparql_get_person_object = SparqlGetPersonMethods()
sparql_post_person_object = SparqlPostPersonMethods()
sparql_get_article_object = SparqlGetArticleMethods()
sparql_post_article_object = SparqlPostArticleMethods()
sparql_get_project_object = SparqlGetProjectMethods()
sparql_post_project_object = SparqlPostProjectMethods()
sparql_get_dataset_object = SparqlGetDatasetMethods()
sparql_post_dataset_object = SparqlPostDatasetMethods()
sparql_get_institution_object = SparqlGetInstitutionMethods()
sparql_post_institution_object = SparqlPostInstitutionMethods()
sparql_get_funder_object = SparqlGetFunderMethods()
sparql_post_funder_object = SparqlPostFunderMethods()