# Generated by Django 3.1.7 on 2021-04-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INCIPIT_CRIS_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
